export const courses = {
  foundation: [
    { name: "Mathematics for data science 1", inputs: ["GAA", "Qz1", "Qz2", "F", "Bonus"], bonus: true },
    { name: "English 1", inputs: ["GAA", "Qz1", "Qz2", "F", "Bonus"], bonus: true },
    { name: "Computational Thinking", inputs: ["GAA", "Qz1", "Qz2", "F", "Bonus"], bonus: true },
    { name: "Statistics for data science 1", inputs: ["GAA", "Qz1", "Qz2", "F", "Bonus"], bonus: 5 },
    { name: "Mathematics for data science 2", inputs: ["GAA", "Qz1", "Qz2", "F", "Bonus"], bonus: true },
    { name: "English 2", inputs: ["GAA", "Qz1", "Qz2", "F", "Bonus"], bonus: true },
    { name: "Intro to Python Programming", inputs: ["GAA1", "GAA2", "Qz1", "F", "PE1", "PE2", "Bonus"], bonus: true },
    { name: "Statistics for data science 2", inputs: ["GAA", "Qz1", "Qz2", "F", "Bonus"], bonus: 5 },
  ],
  diploma: [
    { name: "Machine Learning Foundations", inputs: ["GAA", "Qz1", "Qz2", "F", "Bonus"], bonus: true },
    { name: "Machine Learning Techniques", inputs: ["GAA", "Qz1", "Qz2", "F", "Bonus"], bonus: 3 },
    { name: "Machine Learning Practice", inputs: ["GAA", "OPE1", "OPE2", "KA", "F"], bonus: false },
    { name: "Business Data management", inputs: ["GA", "Q2", "ROE", "F"], bonus: false },
    { name: "Business Analytics", inputs: ["Asgn1", "Asgn2", "Asgn3", "Qz1", "Qz2", "F"], bonus: false },
    { name: "Tools in Data Science", inputs: ["GAA", "ROE1", "P1", "P2", "F", "Bonus"], bonus: true },
    {
      name: "Programming Data structures and algorithms using Python (PDSA)",
      inputs: ["GAA", "Qz1", "Qz2", "OP", "F", "Bonus"],
      bonus: true,
    },
    {
      name: "Database management system (DBMS)",
      inputs: ["GAA1", "GAA2", "GAA3", "Qz1", "Qz2", "OPE", "F", "Bonus"],
      bonus: true,
    },
    { name: "Application development - 1", inputs: ["GLA", "GA", "Qz1", "Qz2", "F", "Bonus"], bonus: true },
    { name: "Programming concepts using Java", inputs: ["GAA", "Qz1", "Qz2", "PE1", "PE2", "F"], bonus: false },
    { name: "System commands", inputs: ["GAA", "Qz1", "OPE", "F", "BPTA", "Bonus"], bonus: true },
    { name: "Application Development - 2", inputs: ["GAA1", "GAA2", "Qz1", "Qz2", "F", "Bonus"], bonus: true },
  ],
  degree: [
    { name: "Software Testing", inputs: ["GAA", "F", "Qz1", "Qz2", "Bonus"], bonus: true },
    { name: "Software Engineering", inputs: ["GAA", "Qz2", "F", "GP1", "GP2", "PP", "CP", "Bonus"], bonus: true },
    { name: "Deep Learning", inputs: ["GAA", "Qz1", "Qz2", "F", "Bonus"], bonus: 5 },
    { name: "AI: Search Methods for Problem Solving", inputs: ["GAA", "Qz1", "Qz2", "F", "Bonus"], bonus: 5 },
    { name: "Strategies for Professional Growth", inputs: ["GAA", "GP", "Qz2", "F", "Bonus"], bonus: true },
    { name: "Introduction to Big Data", inputs: ["GAA", "F", "OPPE1", "OPPE2"], bonus: false },
    { name: "Programming in C", inputs: ["GAA", "GAAP", "Qz1", "OPPE1", "OPPE2", "F"], bonus: false },
    { name: "Deep Learning for CV", inputs: ["GAA", "Qz1", "Qz2", "F", "Bonus"], bonus: true },
    { name: "Managerial Economics", inputs: ["GAA", "Qz1", "Qz2", "F", "Bonus"], bonus: true },
    { name: "Algorithmic Thinking in Bioinformatics", inputs: ["GAA", "Qz1", "Qz2", "F", "Bonus"], bonus: true },
    { name: "Large Language Models", inputs: ["GAA", "Qz1", "Qz2", "F", "Bonus"], bonus: 10 },
    { name: "Speech Technology", inputs: ["GAA", "V", "Qz1", "Qz2", "F", "Bonus"], bonus: true },
    {
      name: "Design Thinking for Data-Driven App Development",
      inputs: ["GAA", "GP1", "GP2", "GP3", "Qz2", "F", "Bonus"],
      bonus: true,
    },
    { name: "Market Research", inputs: ["GAA", "Qz1", "Qz2", "P", "F", "Bonus"], bonus: true },
    { name: "Statistical Computing", inputs: ["GAA", "Qz1", "Qz2", "F", "Bonus"], bonus: true },
    { name: "Advanced Algorithms", inputs: ["GAA", "Qz1", "Qz2", "F", "Bonus"], bonus: true },
    { name: "Game Theory and Strategy", inputs: ["GAA", "Qz1", "Qz2", "F", "Bonus"], bonus: true },
    { name: "Computer System Design", inputs: ["GAA", "Qz1", "Qz2", "F", "CVA"], bonus: false },
    {
      name: "Deep Learning Practice",
      inputs: ["GA", "Quiz1", "Quiz2", "Quiz3", "NPPE1", "NPPE2", "NPPE3", "Viva"],
      bonus: false,
    },
    { name: "Mathematical Foundations of Generative AI", inputs: ["GAA", "Qz1", "Qz2", "F", "OPPE"], bonus: false },
    { name: "Algorithms for Data Science (ADS)", inputs: ["GAA", "Qz2", "F"], bonus: false },
    { name: "MLOPS", inputs: ["GAA", "F", "OPPE1", "OPPE2", "Bonus"], bonus: 5 },
  ],
}
